# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deployment:
    name: "deployment application"
    runs-on: "ubuntu-latest"
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build Image
      run: |
        docker build . -t saahalla/saahalla/product-services:1.0.0
    - name: Docker Push
      run: |
        docker push saahalla/saahalla/product-services:1.0.0
    - name: configure ssh
      env:
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_PRIVATE_KEY" >> ~/.ssh/belajar.pem
        chmod 400 ~/.ssh/belajar.pem
        cat >>~/.ssh/config <<END
        Host staging
          HostName $SSH_HOST
          User $SSH_USERNAME
          IdentityFile ~/.ssh/belajar.pem
          StrictHostKeyChecking=no
        END
    #- name: stop running container
    #  run: ssh staging 'sudo docker container stop learn && sudo docker container rm learn'
    - name: deploy application
      run: ssh staging 'sudo docker rm -f product-services && sudo docker pull saahalla/saahalla/product-services:1.0.0 && sudo docker run -d -p 8088:8088 --name learn-ci --network local-network saahalla/saahalla/product-services:1.0.0'
